
PHONY := __bininst
__bininst :


include scripts/Makefile.lib


# Install bin
# ---------------------------------------------------------------------------
inst_bindir := $(inst_path)/bin
inst-bin    := $(single) $(multi)

echo_bininst = INSTALL $@
cmd_bininst = mkdir -p $(inst_bindir); cp -r $@ $(inst_bindir)


__bininst : $(subdir) $(inst-bin)
	@:

$(inst-bin) :
	$(call cmd,bininst)

$(subdir) :
	$(Q)$(MAKE) $(bininst)=$@


PHONY += $(subdir) $(inst-bin)

.PHONY: $(PHONY)
