
PHONY := __clean
__clean :


include scripts/Makefile.lib


# Clean
# ---------------------------------------------------------------------------
clean-files := $(obj) $(obj-deps) $(single) $(multi) \
		$(lib) $(lib-deps) $(curlib) $(arlib) $(shlib)

echo_clean = CLEAN   $(src)
cmd_clean = rm -rf $(clean-files)


__clean : $(subdir)
	$(call cmd,clean)

$(subdir) :
	$(Q)$(MAKE) $(clean)=$@


PHONY += $(subdir)

.PHONY: $(PHONY)
